# use Debian-Stretch-slim for raspbian compability and minimal size
FROM logi_loader_x86

WORKDIR /bitstreams
COPY pushbuttons_leds_assign.bit .

#ENTRYPOINT [ "/logipi/logi_loader" ]

CMD ["/bitstreams/pushbuttons_leds_assign.bit"]
#CMD ["bash"]
