# use Debian-Stretch-slim for raspbian compability and minimal size
FROM logi_loader_x86

WORKDIR /bitstreams
COPY pushbuttons_leds_assign.bit .

# pass the command (ie the bitstream to upload) to the base container
CMD ["/bitstreams/pushbuttons_leds_assign.bit"]

